import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy Policy" };

export default function PrivacyPage() {
  return (
    <div className="max-w-2xl flex flex-col gap-6">
      <h1 className="text-2xl font-bold">Privacy Policy</h1>
      <div className="prose dark:prose-invert text-sm text-slate-600 dark:text-slate-400 space-y-4">
        <p>AMIRNET Trainer is an independent preparation tool. It is not affiliated with NITE or any official examination body.</p>
        <p>All progress data is stored locally in your browser (localStorage). No personal data is transmitted to our servers unless you create an account.</p>
        <p>We do not sell your data. We do not share your data with third parties.</p>
        <p>Scores, simulations, and predictions generated by this app are unofficial and for practice purposes only.</p>
      </div>
    </div>
  );
}
