"use client";

import { useLang } from "@/contexts/LanguageContext";

export default function PrivacyPage() {
  const { lang } = useLang();
  const isHe = lang === "he";

  const title = isHe ? "מדיניות פרטיות" : "Privacy Policy";

  const paragraphs = isHe
    ? [
        "Amirnet Coach הוא כלי עצמאי להכנה לאמירנט. הוא אינו קשור למאל״ו, ל-NITE או לכל גוף בחינה רשמי.",
        "התקדמות, ציונים, הגדרות ונתוני תרגול נשמרים באופן מקומי בדפדפן של המשתמש, אלא אם בעתיד תחובר מערכת חשבונות אמיתית.",
        "הציונים, התחזיות וההמלצות באפליקציה אינם רשמיים ומיועדים לתרגול בלבד.",
        "איננו מוכרים מידע אישי ואיננו משתפים מידע אישי עם צדדים שלישיים.",
      ]
    : [
        "Amirnet Coach is an independent AMIRNET preparation tool. It is not affiliated with NITE or any official examination body.",
        "Progress, scores, settings, and practice data are stored locally in the user's browser unless a real account system is added in the future.",
        "Scores, predictions, and recommendations generated by this app are unofficial and for practice purposes only.",
        "We do not sell personal data and we do not share personal data with third parties.",
      ];

  return (
    <article
      dir={isHe ? "rtl" : "ltr"}
      style={{
        maxWidth: 720,
        marginInline: "auto",
        width: "100%",
        display: "flex",
        flexDirection: "column",
        gap: "1.25rem",
        boxSizing: "border-box",
      }}
    >
      <h1
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "clamp(1.5rem, 5vw, 2rem)",
          fontWeight: 800,
          color: "var(--ink)",
          margin: 0,
          textAlign: isHe ? "right" : "left",
        }}
      >
        {title}
      </h1>
      <div
        style={{
          display: "flex",
          flexDirection: "column",
          gap: "1rem",
          color: "var(--ink-soft)",
          fontSize: "0.95rem",
          lineHeight: 1.7,
          textAlign: isHe ? "right" : "left",
        }}
      >
        {paragraphs.map((p, i) => (
          <p key={i} style={{ margin: 0, overflowWrap: "anywhere" }}>
            {p}
          </p>
        ))}
      </div>
    </article>
  );
}
