export interface Translations {
  nav: { dashboard: string; practice: string; simulation: string; vocab: string; review: string; challenge: string; pricing: string; account: string; admin: string; learningEngine: string };
  home: { tagline: string; hero: string; heroSub: string; startFree: string; runSim: string; disclaimer: string };
  practice: { title: string; pickMode: string; startSession: string; question: string; of: string; submit: string; next: string; correct: string; incorrect: string; sessionDone: string; accuracy: string; timeUsed: string; reviewMistakes: string; practiceAgain: string; difficulty: string; mixed: string; easy: string; medium: string; hard: string };
  vocab: { title: string; flip: string; knew: string; didntKnow: string; star: string; shuffle: string; new: string; learning: string; strong: string; mastered: string; dueToday: string; swipeRight: string; swipeLeft: string; vocabDisclaimer: string };
  simulation: { title: string; standard: string; withPilot: string; quick: string; pilotOnly: string; section: string; timeLeft: string; pilotWarning: string; score: string; unofficial: string; exemption: string; breakdown: string; };
  dashboard: { greeting: string; goalProgress: string; streak: string; weakAreas: string; vocabDue: string; recommended: string; noData: string };
  common: { loading: string; save: string; cancel: string; close: string; settings: string; darkMode: string; lightMode: string; hebrew: string; english: string; back: string; start: string; finish: string; empty: string };
}

export const he: Translations = {
  nav: { dashboard: "לוח בקרה", practice: "תרגול", simulation: "הדמיה", vocab: "מילים", review: "סקירה", challenge: "אתגר", pricing: "תמחור", account: "חשבון", admin: "ניהול", learningEngine: "מנוע למידה" },
  home: { tagline: "הכנה עצמאית לאמירנט", hero: "תתאמן באנגלית ברמת אמירנט — מילון חכם, דרילים, הדמיות.", heroSub: "תרגל קריאה, מילים, ניסוח מחדש ותזמון מבחן. לא קשור לנית.", startFree: "התחל חינם →", runSim: "הדמיה מלאה", disclaimer: "כלי הכנה עצמאי לאמירנט. לא קשור לנית. ציונים, הדמיות ותחזיות הם לא רשמיים." },
  practice: { title: "תרגול", pickMode: "בחר קטגוריה", startSession: "התחל סשן", question: "שאלה", of: "מתוך", submit: "שלח תשובה", next: "הבאה", correct: "נכון!", incorrect: "לא נכון", sessionDone: "הסשן הסתיים", accuracy: "דיוק", timeUsed: "זמן", reviewMistakes: "סקור שגיאות", practiceAgain: "תרגל שוב", difficulty: "רמת קושי", mixed: "מעורב", easy: "קל", medium: "בינוני", hard: "קשה" },
  vocab: { title: "מילון", flip: "הפוך כרטיס", knew: "ידעתי ✓", didntKnow: "לא ידעתי", star: "סמן", shuffle: "ערבב", new: "חדש", learning: "לומד", strong: "חזק", mastered: "שלטתי", dueToday: "לתרגול היום", swipeRight: "החלק ימינה — ידעתי", swipeLeft: "החלק שמאלה — לא ידעתי", vocabDisclaimer: "רשימת המילים מבוססת על חומר לימוד של משתמשים. זו אינה רשימה רשמית של נית." },
  simulation: { title: "הדמיית אמירנט", standard: "אמירנט סטנדרטי", withPilot: "אמירנט+ עם פיילוט", quick: "תרגול מהיר", pilotOnly: "סעיפי פיילוט בלבד", section: "סעיף", timeLeft: "זמן שנותר", pilotWarning: "אלו סעיפי ניסוי. שגיאות לא יורידו את הציון. תשובות נכונות עשויות להוסיף עד 2 נקודות בונוס.", score: "ציון", unofficial: "ציון זה אינו רשמי ומיועד לאימון בלבד. לא קשור לנית או מאל\"מ.", exemption: "רמת פטור — ביצוע מצוין", breakdown: "פירוט לפי סעיף" },
  dashboard: { greeting: "שלום", goalProgress: "התקדמות יומית", streak: "רצף ימים", weakAreas: "נקודות לשיפור", vocabDue: "מילים לתרגול היום", recommended: "פעילות מומלצת", noData: "השלם את הסשן הראשון כדי לראות נתונים" },
  common: { loading: "טוען...", save: "שמור", cancel: "ביטול", close: "סגור", settings: "הגדרות", darkMode: "מצב לילה", lightMode: "מצב יום", hebrew: "עברית", english: "English", back: "חזרה", start: "התחל", finish: "סיים", empty: "אין נתונים עדיין" },
};

export const en: Translations = {
  nav: { dashboard: "Dashboard", practice: "Practice", simulation: "Simulation", vocab: "Vocab", review: "Review", challenge: "Challenge", pricing: "Pricing", account: "Account", admin: "Admin", learningEngine: "Learn" },
  home: { tagline: "Independent AMIRNET Prep", hero: "Practice AMIRNET-style English with smart drills, simulations, and swipe vocabulary.", heroSub: "Train reading, vocabulary, restatements, and exam timing. Not affiliated with NITE.", startFree: "Start for free →", runSim: "Run a simulation", disclaimer: "Independent AMIRNET preparation tool. Not affiliated with NITE. Scores, simulations, and predictions are unofficial." },
  practice: { title: "Practice", pickMode: "Pick a mode", startSession: "Start session", question: "Question", of: "of", submit: "Submit answer", next: "Next", correct: "Correct!", incorrect: "Incorrect", sessionDone: "Session complete", accuracy: "Accuracy", timeUsed: "Time", reviewMistakes: "Review mistakes", practiceAgain: "Practice again", difficulty: "Difficulty", mixed: "Mixed", easy: "Easy", medium: "Medium", hard: "Hard" },
  vocab: { title: "Vocab Trainer", flip: "Flip card", knew: "I knew it ✓", didntKnow: "Review again", star: "Star", shuffle: "Shuffle", new: "New", learning: "Learning", strong: "Strong", mastered: "Mastered", dueToday: "Due today", swipeRight: "Swipe right — I knew it", swipeLeft: "Swipe left — review again", vocabDisclaimer: "This vocabulary deck is based on user-provided study material. It is not an official NITE word list." },
  simulation: { title: "AMIRNET Simulation", standard: "Standard AMIRNET", withPilot: "AMIRNET+ with Pilot", quick: "Quick Practice", pilotOnly: "Pilot sections only", section: "Section", timeLeft: "Time left", pilotWarning: "These are experimental sections. Mistakes will not lower your score. Correct answers may add up to 2 bonus points.", score: "Score", unofficial: "This score estimate is unofficial and for practice only. Not affiliated with NITE or MALAM.", exemption: "Exemption level — strong performance", breakdown: "Section breakdown" },
  dashboard: { greeting: "Hello", goalProgress: "Daily goal", streak: "Day streak", weakAreas: "Weak areas", vocabDue: "Vocab due today", recommended: "Recommended activity", noData: "Complete your first session to see data" },
  common: { loading: "Loading…", save: "Save", cancel: "Cancel", close: "Close", settings: "Settings", darkMode: "Dark mode", lightMode: "Light mode", hebrew: "עברית", english: "English", back: "Back", start: "Start", finish: "Finish", empty: "Nothing here yet" },
};
