/**
 * Curated Hebrew translations for Sentence Completion answer choices.
 *
 * The seed dictionary at vocab.normalized.json covers about 200 of the
 * ~720 unique English choice strings across the SC bank — mostly everyday
 * vocabulary, with very low coverage of the AMIRNET-tier hard / medium
 * choices (tendentious, hedging, discursive, etc.). This map fills the
 * remaining gap so the SC glossary panel always renders a real Hebrew
 * translation per choice instead of "(אין תרגום)".
 *
 * Keys are lowercased and stripped per the same normalize rule used by
 * explain-glossary.ts. Values use academic-register Hebrew that matches
 * the meaning the word carries in its SC context.
 *
 * Adding a new SC item with novel choices? Either extend this map or
 * extend vocab.normalized.json — the lookup in explain-glossary.ts
 * consults the seed first, then this map.
 */
export const SC_CHOICE_GLOSSARY: Record<string, string> = {
  "abstract": "מופשט",
  "abstraction": "הפשטה, רעיון מופשט",
  "accidental": "מקרי, בלתי מכוון",
  "accommodate": "להכיל, להתאים, לאכלס",
  "accusations": "האשמות",
  "acknowledged": "הוכר, הודה ב-",
  "adaptive": "מסתגל, אדפטיבי",
  "adequate": "מספיק, הולם",
  "adjourned": "נדחה, הופסק (ישיבה)",
  "adverse": "שלילי, פוגע, מנוגד",
  "aesthetic": "אסתטי, יופייני",
  "alarmist": "מעורר בהלה, מפחיד",
  "alienate": "להרחיק, לזרזף, להפוך לזר",
  "allegory": "אלגוריה, משל",
  "allusion": "רמיזה",
  "amplify": "להגביר, להעצים",
  "anachronism": "אנכרוניזם, חוסר התאמה לזמן",
  "androcentric": "אנדרוצנטרי, ממוקד-גבר",
  "anecdotal": "אנקדוטלי, מבוסס סיפור אישי",
  "anomalous": "חריג, שלא לפי הדפוס",
  "appetite": "תיאבון, חשק",
  "applied": "יישומי, מיושם",
  "artificial": "מלאכותי",
  "assertiveness": "אסרטיביות, נחרצות",
  "asymmetric": "אסימטרי, לא סימטרי",
  "audited": "עבר ביקורת, נבדק",
  "austerity": "צנע, ריסון תקציבי",
  "autocratic": "אוטוקרטי, רודני",
  "automate": "להפוך לאוטומטי",
  "barren": "עקר, ריק, חסר תוכן",
  "belligerent": "תוקפני, לוחמני",
  "beneficial": "מועיל",
  "biased": "מוטה",
  "boost": "להגביר, חיזוק",
  "breakthroughs": "פריצות דרך",
  "breathable": "נושם, חדיר לאוויר",
  "brief": "קצר, תמציתי",
  "bureaucratic": "ביורוקרטי",
  "cancel": "לבטל",
  "candor": "כנות, גילוי לב",
  "captivate": "לרתק, לכבוש את הלב",
  "careless": "רשלני, חסר אכפתיות",
  "ceremonial": "טקסי",
  "chronicle": "לתעד, כרוניקה",
  "chronology": "כרונולוגיה, סדר זמנים",
  "circumspection": "זהירות, שיקול דעת",
  "circumventing": "עוקף, מתחמק מ-",
  "clause": "סעיף, פסקה משפטית",
  "clinical": "קליני, רפואי",
  "codification": "קודיפיקציה, הכנסה לקוד",
  "codified": "מקודד, מעוגן בקוד",
  "coercive": "כפייתי, כופה",
  "coherence": "קוהרנטיות, לכידות",
  "cohesion": "לכידות, גיבוש",
  "combine": "לשלב, לחבר",
  "commercialize": "להפוך למסחרי",
  "communitarian": "קהילתני",
  "compelling": "משכנע, מכריח",
  "complicate": "לסבך",
  "comply": "לציית, להיענות",
  "complying with": "ציות ל-",
  "composure": "שלוות נפש, איפוק",
  "compressed": "דחוס, מכווץ",
  "compromise": "פשרה, להתפשר",
  "compromised": "נפגע, אבדה שלמותו",
  "concessions": "ויתורים, הסכמים זוטא",
  "concurrent": "מקביל, סימולטני",
  "confirmed": "אושר, אומת",
  "conform": "להתאים, לציית לנורמה",
  "confuse": "לבלבל",
  "confused": "מבולבל",
  "consensus": "קונצנזוס, הסכמה רחבה",
  "conservative": "שמרני",
  "conserve": "לשמר, לחסוך",
  "consolidate": "לאחד, לבסס",
  "contingent": "תלוי בנסיבות, מותנה",
  "contrived": "מאולץ, מלאכותי",
  "controversial": "שנוי במחלוקת",
  "convened": "התכנס, הוזעק",
  "conventional": "מסורתי, מקובל",
  "copied": "הועתק",
  "correction": "תיקון",
  "correlation": "מתאם, קורלציה",
  "cramped": "צפוף, דחוס",
  "curb": "לרסן, לבלום",
  "curiosity": "סקרנות",
  "curious": "סקרן",
  "decorate": "לקשט",
  "decoration": "קישוט",
  "decorative": "קישוטי",
  "defer": "לדחות, להעביר סמכות",
  "deferential": "מתחשב, מכבד",
  "defunct": "לא פעיל יותר, מת",
  "degraded": "שופל, שקעה איכותו",
  "delay": "לעכב, עיכוב",
  "deleted": "נמחק",
  "demolish": "להרוס, להחריב",
  "demonstrable": "ניתן להוכחה",
  "denied": "הוכחש, נדחה",
  "dependence": "תלות",
  "dependent": "תלוי",
  "derivative": "נגזרת, חסר מקוריות",
  "destabilize": "לערער יציבות",
  "detached": "מנותק, אדיש",
  "deviate": "לסטות",
  "devout": "אדוק, מסור",
  "diction": "סגנון דיבור, בחירת מילים",
  "didacticism": "דידקטיות, מוסר השכל",
  "diet": "תזונה, דיאטה",
  "difficulty": "קושי",
  "diplomatic": "דיפלומטי",
  "directive": "הוראה, צו",
  "disagree": "לחלוק על, לא להסכים",
  "disappear": "להיעלם",
  "discard": "להשליך, לזרוק",
  "discourage": "לרפות ידיים, להניא",
  "discredit": "להכפיש, לערער אמינות",
  "discretion": "שיקול דעת",
  "discriminatory": "מפלה",
  "discursive": "שיחני, של שיח ציבורי",
  "dismantled": "פורק, התפרק",
  "dismiss": "לפטר, לדחות, לבטל",
  "dismissive": "מזלזל, פוטר בקלות",
  "disparity": "פער, אי-שוויון",
  "disrupt": "לשבש, להפריע",
  "disruption": "שיבוש",
  "disruptive": "משבש, פורץ דרך",
  "dissociation": "ניתוק, דיסוציאציה",
  "distant": "רחוק",
  "document": "מסמך, לתעד",
  "documentation": "תיעוד",
  "documented": "מתועד",
  "dominant": "דומיננטי, שולט",
  "double": "כפול, להכפיל",
  "dramatize": "להמחיז, להפריז",
  "economic": "כלכלי",
  "educate": "לחנך",
  "efficacy": "יעילות, אפקטיביות",
  "elevated": "מוגבה, רם",
  "empathy": "אמפתיה, הזדהות",
  "emphasis": "דגש, הדגשה",
  "empirical": "אמפירי, מבוסס תצפית",
  "enclosed": "סגור, מוקף",
  "endorsement": "תמיכה, אישור",
  "entertain": "לבדר, להעלות (רעיון)",
  "entrenched": "מבוצר, מושרש עמוק",
  "equalize": "להשוות, ליצור שוויון",
  "equitable": "הוגן, צודק",
  "erode": "לשחוק",
  "escalate": "להסלים, להחריף",
  "escalation": "הסלמה",
  "escalations": "הסלמות",
  "ethical": "אתי",
  "ethics": "אתיקה",
  "eurocentric": "אירוצנטרי, ממוקד אירופה",
  "evacuate": "לפנות (אזור)",
  "evasiveness": "התחמקות, חמקנות",
  "exaggerate": "להגזים",
  "exclusive": "בלעדי, ייחודי",
  "exemplary": "מופתי",
  "extraneous": "חיצוני, לא רלוונטי",
  "fabricate": "לזייף, להמציא",
  "factual": "עובדתי",
  "falsifiable": "ניתן להפרכה",
  "feasible": "ישים, מעשי",
  "fecund": "פורה, יצרני",
  "feminist": "פמיניסטי",
  "forbid": "לאסור",
  "forbidden": "אסור",
  "foreign": "זר, חיצוני",
  "formality": "פורמליות, רשמיות",
  "formulaic": "סטריאוטיפי, על פי נוסחה",
  "foster": "לטפח, לעודד",
  "fragment": "שבר, רסיס",
  "generalized": "כללי, הוכלל",
  "genetic": "גנטי",
  "glowing": "זוהר, נלהב",
  "growth": "צמיחה",
  "guarantee": "להבטיח, ערובה",
  "harsh": "קשה, חמור",
  "hedging": "חמיקני, מגדר סיכון",
  "hesitant": "מהוסס",
  "hesitate": "להסס",
  "highlight": "להדגיש",
  "hinder": "להפריע, לעכב",
  "historical": "היסטורי",
  "historicism": "היסטוריציזם",
  "hobby": "תחביב",
  "identical": "זהה",
  "imaginary": "דמיוני",
  "implementation": "יישום, ביצוע",
  "implied": "משתמע, רמוז",
  "important": "חשוב",
  "inadequate": "לא מספיק, לא הולם",
  "incompatible": "לא תואם, סותר",
  "inconvenience": "אי-נוחות",
  "incremental": "הדרגתי, בצעדים קטנים",
  "indefensible": "בלתי ניתן להגנה, מקומם",
  "indeterminacy": "אי-ודאות, חוסר הכרעה",
  "indifference": "אדישות",
  "inherited": "הוריש, נורש",
  "innovative": "חדשני",
  "instance": "מקרה, דוגמה",
  "intangible": "לא מוחשי, ערטילאי",
  "interfere": "להפריע, להתערב",
  "intermittent": "לסירוגין, אקראי",
  "internalize": "להפנים",
  "intersectional": "אינטרסקציונלי, חוצה זהויות",
  "intervention": "התערבות",
  "interventionist": "התערבותני",
  "intransigent": "עקשני, בלתי מתפשר",
  "intricate": "מורכב, סבוך",
  "invitation": "הזמנה",
  "irony": "אירוניה",
  "irreconcilable": "בלתי ניתן להשלמה, מנוגד יסודית",
  "irregular": "לא סדיר",
  "irrelevant": "לא רלוונטי",
  "landscape": "נוף, שטח",
  "lazily": "בעצלתיים",
  "legalize": "להפוך לחוקי",
  "length": "אורך, משך",
  "liberal": "ליברלי",
  "libertarian": "ליברטריאני",
  "linear": "לינארי, ישר",
  "linguistic": "לשוני",
  "lower": "להוריד, נמוך יותר",
  "lukewarm": "פושר, חסר התלהבות",
  "manufacture": "לייצר",
  "material": "חומר, חומרי",
  "measurable": "ניתן למדידה",
  "mechanical": "מכני",
  "merger": "מיזוג",
  "minimal": "מינימלי",
  "minor": "קל, קטין",
  "mitigated": "רוכך, הוקל",
  "mixed": "מעורב",
  "modern": "מודרני",
  "modernize": "למודרן, לחדש",
  "monitor": "לפקח, לעקוב",
  "monumental": "מונומנטלי, עצום",
  "moral": "מוסרי",
  "multiply": "להכפיל",
  "nascent": "מתהווה, בראשיתי",
  "navigate": "לנווט",
  "negative": "שלילי",
  "negligible": "זניח",
  "negotiate": "לנהל משא ומתן",
  "noncommittal": "לא מחייב, חמקני",
  "observe": "להתבונן, לציין",
  "obsolete": "מיושן, לא רלוונטי",
  "obstacle": "מכשול",
  "obstacles": "מכשולים",
  "omission": "השמטה",
  "omniscient": "כל-יודע",
  "optimistic": "אופטימי",
  "optional": "אופציונלי, רשות",
  "ordinary": "רגיל, שגרתי",
  "originality": "מקוריות",
  "ornamental": "קישוטי",
  "ornate": "מפואר, מקושט יתר על המידה",
  "ostensibly secular": "חילוני לכאורה",
  "outcry": "זעקה ציבורית, מחאה",
  "outdated": "מיושן",
  "overlook": "להתעלם מ-, להחמיץ",
  "override": "לבטל החלטה, לעקוף",
  "oversight": "פיקוח, השגחה",
  "overwhelm": "להציף, להכריע",
  "participatory": "השתתפותי",
  "passive": "פסיבי",
  "paternalistic": "פטרנליסטי",
  "pathological": "פתולוגי, חולני",
  "peaceful": "שליו, רגוע",
  "pedantic": "פדנטי",
  "permission": "רשות, היתר",
  "pervasive": "נפוץ, מקיף",
  "plastic": "פלסטי, גמיש",
  "poignant": "נוגע ללב, חד",
  "polluted": "מזוהם",
  "popularity": "פופולריות",
  "portable": "נייד",
  "portrayal": "תיאור, ייצוג",
  "precedent": "תקדים",
  "preconceptions": "דעות קדומות",
  "predictable": "צפוי",
  "preference": "העדפה",
  "preliminary": "ראשוני, מקדים",
  "prescribe": "לרשום (תרופה), להמליץ",
  "preservation": "שימור",
  "preserved": "נשמר",
  "privatize": "להפריט",
  "proactive": "יוזם, פרואקטיבי",
  "procedural": "פרוצדורלי",
  "proficiency": "שליטה, מיומנות",
  "profligacy": "בזבזנות, חוסר ריסון",
  "projected": "צפוי, חזוי",
  "promising": "מבטיח",
  "proofread": "להגיה",
  "provocative": "פרובוקטיבי, מעורר תגובה",
  "prudent": "זהיר, נבון",
  "publicize": "לפרסם",
  "publicized": "פורסם",
  "punitive": "ענישתי",
  "quantitative": "כמותי",
  "randomization": "אקראיות, רנדומיזציה",
  "randomness": "אקראיות",
  "rawlsian": "רוולסיאני (על פי ג'ון רולס)",
  "reactive": "תגובתי",
  "realism": "ריאליזם",
  "reckless": "פזיז",
  "reconsider": "לשקול מחדש",
  "reconstructive": "שחזורי, של שחזור",
  "record": "תעודה, לרשום",
  "recorded": "נרשם, מוקלט",
  "recover": "להתאושש",
  "redirected": "הופנה מחדש",
  "redistribute": "לחלק מחדש",
  "redistributed": "חולק מחדש",
  "refined": "מעודן, מזוקק",
  "reflect": "לשקף, להרהר",
  "refuted": "הופרך",
  "regular": "סדיר, קבוע",
  "regulate": "להסדיר, לפקח",
  "regulated": "מוסדר",
  "reject": "לדחות",
  "rejection": "דחייה",
  "relativism": "רלטיביזם",
  "reliable": "אמין",
  "religiously homogeneous": "אחיד מבחינה דתית",
  "reluctance": "חוסר רצון",
  "remove": "להסיר",
  "repeat": "לחזור",
  "replacement": "החלפה, מחליף",
  "replicable": "ניתן לשחזור",
  "replicate": "לשחזר ניסוי, לשכפל",
  "replicated": "שוחזר, שוכפל",
  "resistance": "התנגדות",
  "retracted": "חזר בו, נסוג",
  "retrospective": "רטרוספקטיבי, של מבט לאחור",
  "review": "סקירה, לסקור",
  "revisited": "נבחן מחדש",
  "rhetorical": "רטורי",
  "rigorous": "קפדני, מחמיר",
  "rigorously": "בקפדנות",
  "rumor": "שמועה",
  "rumors": "שמועות",
  "salary": "משכורת",
  "satisfied": "מרוצה",
  "scatter": "לפזר",
  "sceptical": "ספקני",
  "schedule": "לוח זמנים, לתזמן",
  "scope": "היקף, טווח",
  "secondary": "משני",
  "self-effacing": "צנוע, מצניע את עצמו",
  "self-reflexive": "תגובתי-עצמי, מודע לעצמו",
  "sharpen": "לחדד",
  "shortened": "קוצר, התקצר",
  "simple": "פשוט",
  "simplification": "פישוט",
  "simplify": "לפשט",
  "skepticism": "סקפטיות, ספקנות",
  "skewed": "מוטה, מעוות",
  "skipped": "דולג",
  "sluggish": "איטי, חסר חיות",
  "social": "חברתי",
  "soundtracks": "פסקולים",
  "sparse": "דליל, מועט",
  "speculative": "השערתי, ספקולטיבי",
  "spent": "הוצא, בילה",
  "spontaneous": "ספונטני",
  "sporadic": "ספורדי, אקראי",
  "sporadically": "באופן ספורדי",
  "stabilize": "לייצב",
  "stagnate": "לקפוא, לדשדש",
  "standardize": "לתקנן",
  "statistical": "סטטיסטי",
  "statutory": "חוקי, על פי חוק",
  "strength": "כוח, חוזק",
  "strengthen": "לחזק",
  "structural": "מבני",
  "subjective": "סובייקטיבי",
  "submissive": "כנוע, צייתני",
  "subordinate": "לכפוף, פקודי",
  "subsidize": "לסבסד",
  "substantial": "משמעותי, מהותי",
  "superficial": "שטחי",
  "supplement": "להוסיף, תוסף",
  "suppress": "לדכא, להשתיק",
  "symbolic": "סמלי",
  "symmetry": "סימטריה",
  "systemic": "מערכתי, סיסטמי",
  "technical": "טכני",
  "tendentious": "מגמתי, מוטה",
  "tentative": "מהוסס, ניסיוני",
  "test": "בחינה, לבחון",
  "testimonies": "עדויות",
  "theocratic": "תיאוקרטי, של ממשל דת",
  "theoretical": "תיאורטי",
  "therapeutic": "טיפולי",
  "threaten": "לאיים",
  "tirelessly": "ללא ליאות",
  "tolerance": "סבלנות, סובלנות",
  "toxic": "רעיל",
  "transactional": "עסקאתי",
  "transferred": "הועבר",
  "transient": "חולף, זמני",
  "transparency": "שקיפות",
  "transported": "הוסע",
  "unconscious": "לא מודע",
  "uncovered": "חשף, גילה",
  "unilateral": "חד-צדדי",
  "universal": "אוניברסלי, כללי",
  "unreliable": "לא אמין",
  "untestable": "לא ניתן לבדיקה",
  "unwarranted": "לא מוצדק, לא מבוסס",
  "urgency": "דחיפות",
  "utilitarian": "תועלתני",
  "validated": "אומת, אושר",
  "variable": "משתנה",
  "verbose": "מילולי יתר על המידה",
  "verified": "אומת, אושר",
  "vilify": "להכפיש",
  "vivid": "חי, חי בצבעיו",
  "vocabulary": "אוצר מילים",
  "vociferous": "קולני, רעשני",
  "voluntary": "וולונטרי, מרצון",
  "waive": "לוותר על",
  "wardrobe": "ארון בגדים",
  "weaken": "להחליש",
  "widen": "להרחיב",
  "withdraw": "למשוך בחזרה, לסגת",
  "withhold": "לעכב, להימנע מלמסור",
  "worsen": "להחמיר",
  // ── Second pass: words that survived seed + lemmatization fallback.
  "creation": "יצירה",
  "hazardous": "מסוכן",
  "functional": "פונקציונלי, ענייני",
  "experimental": "ניסיוני",
  "promotion": "קידום",
  "seasonal": "עונתי",
  "elimination": "ביטול, סילוק",
  "assimilation": "התבוללות, הטמעה",
  "costly": "יקר, עתיר עלות",
  "personal": "אישי",
  "isolation": "בידוד",
  "cooperation": "שיתוף פעולה",
  "celebration": "חגיגה",
  "legislative": "מחוקק, של חקיקה",
  "institutional": "מוסדי",
  "constitutional": "חוקתי",
  "ambiguously": "באופן עמום, רב-משמעי",
  "clearly": "בבירור",
  "precisely": "בדיוק, במדויק",
  "reluctantly": "באי-רצון",
  "collaborative": "שיתופי, של שיתוף פעולה",
  "loosely": "בצורה רופפת, באופן חלש",
  "marginally": "באופן שולי",
  "casually": "באופן מזדמן, לא רשמי",
};
